# create numpy array with randam numbers

In [1]:
import numpy as np

# rand()

In [3]:
array_1=np.random.rand(4)
print(array_1)

[0.47706935 0.73771907 0.18104187 0.55910121]


In [5]:
array_2=np.random.rand(5)
print(array_2)

[0.27897978 0.39582818 0.75110277 0.08474843 0.88450136]


In [8]:
array_3=np.random.rand(2,4)
print(array_3)

[[0.37778877 0.23626785 0.45194732 0.79548688]
 [0.02269078 0.37295135 0.28224518 0.41696176]]


# randn()

In [9]:
array_1=np.random.randn(2,5)
print(array_1)

[[ 0.08034556  0.03154428 -2.56955904 -0.09206419 -1.07338855]
 [-0.15125863 -0.91059335  0.57337409 -0.34830999 -0.6988885 ]]


# ranf()

In [11]:
array_1=np.random.ranf(5)
print(array_1)

[0.22290463 0.4731199  0.70333383 0.29624465 0.0695548 ]


In [12]:
array_2=np.random.ranf(9)
print(array_1)

[0.22290463 0.4731199  0.70333383 0.29624465 0.0695548 ]


# randint()

In [13]:
array_1=np.random.randint(2)
print(array_1)

0


In [14]:
array_2=np.random.randint(3,6)
print(array_2)

5


In [15]:
array_3=np.random.randint(5,20,5)
print(array_3)

[ 8 12 10 12 15]
