In [1]:
import numpy as np

In [2]:
A=np.arange(1,6)
C=np.arange(1,26).reshape(5,5)

In [3]:
A

array([1, 2, 3, 4, 5])

In [4]:
C

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [5]:
A[2]

3

In [6]:
C[2,3]

14

In [7]:
A[2] = -3

In [8]:
C[2,3] = -14

In [9]:
A

array([ 1,  2, -3,  4,  5])

In [10]:
C

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13, -14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25]])

# Negative indexing

In [11]:
C[2]

array([ 11,  12,  13, -14,  15])

In [12]:
C[4]

array([21, 22, 23, 24, 25])

In [13]:
C[-4]

array([ 6,  7,  8,  9, 10])

In [14]:
C[-5]

array([1, 2, 3, 4, 5])

In [15]:
C[-1] = [0,0,0,0,0]

In [16]:
print(C)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13 -14  15]
 [ 16  17  18  19  20]
 [  0   0   0   0   0]]


In [17]:
C[-2]=2

In [18]:
print(C)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13 -14  15]
 [  2   2   2   2   2]
 [  0   0   0   0   0]]


In [19]:
C[-2]=1

In [20]:
print(C)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13 -14  15]
 [  1   1   1   1   1]
 [  0   0   0   0   0]]


# Slicing Array

In [21]:
C[0:3,2]

array([ 3,  8, 13])

In [23]:
C[2,0:3]

array([11, 12, 13])

# Exercise 1 obtain the following element one by one from array c

In [25]:
C[1,1:3]

array([7, 8])

In [28]:
C[0:4,0]

array([ 1,  6, 11,  1])

In [30]:
C[1:5,0]

array([ 6, 11,  1,  0])

# Exercise 2 obtain the elements [8,9],[13,-14]] from array C

In [36]:
C[1:3,2:4]

array([[  8,   9],
       [ 13, -14]])

In [37]:
C[: : 2,: : 2]

array([[ 1,  3,  5],
       [11, 13, 15],
       [ 0,  0,  0]])

In [38]:
C[1::2,::2]

array([[ 6,  8, 10],
       [ 1,  1,  1]])

In [39]:
C[::3,1::3]

array([[2, 5],
       [1, 1]])

In [40]:
C[::4,1::4]

array([[2],
       [0]])