In [1]:
from numpy import asmatrix,arange

In [2]:
a= asmatrix(arange(1,10).reshape(3,3))

In [3]:
a

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

# Flatten (is convert one dimension matrix)

In [4]:
a.flatten()

matrix([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

# Frobenious norm of a matrix

In [5]:
m=asmatrix(arange(1,17).reshape(4,4))

In [6]:
m

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

In [9]:
m[0,1] = 0
m[1,3] = 0

In [10]:
m

matrix([[ 1,  0,  3,  4],
        [ 5,  6,  7,  0],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])