In [1]:
import numpy as np

# one dimenssional array

In [2]:
a1=np.array([1,2,3,4,5])

In [3]:
a1

array([1, 2, 3, 4, 5])

# Two dimensional array

In [4]:
a2=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [5]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# Arange method 

In [6]:
ar=np.arange(1,9) 

In [7]:
print(ar)

[1 2 3 4 5 6 7 8]


# Reshape methon

In [8]:
ar.reshape([2,4])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
ar

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
ar.shape=(2,4)

In [11]:
ar

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
a2.shape

(2, 5)

In [13]:
a1.shape

(5,)

In [14]:
ar.shape

(2, 4)

In [15]:
a3=np.array([1,3,4,'a string'])

In [16]:
print(a3) # it is directly convert to the srting

['1' '3' '4' 'a string']


In [17]:
a3

array(['1', '3', '4', 'a string'], dtype='<U11')

# Identity method(matrix)

In [18]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [19]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.identity(1)

array([[1.]])

# Zeros Matrix

In [21]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
a1


array([1, 2, 3, 4, 5])

In [24]:
a1*2

array([ 2,  4,  6,  8, 10])

In [25]:
a2*3

array([[ 3,  6,  9, 12, 15],
       [18, 21, 24, 27, 30]])

In [26]:
a1+2

array([3, 4, 5, 6, 7])

In [27]:
a1+=2

In [28]:
a1

array([3, 4, 5, 6, 7])

In [29]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [30]:
a1+a2

array([ 7,  9, 11, 13, 15])

# Assingment question

In [38]:
# x=np.array([1,2,3,],[5,6,7]) is the valid statement (true,false)

In [34]:
x=np.array([1,2,3,],[5,6,7])

TypeError: Field elements must be 2- or 3-tuples, got '5'

In [35]:
# ans is false

In [36]:
x=np.array([[1,2,3],[5,6,7]])

In [37]:
x

array([[1, 2, 3],
       [5, 6, 7]])