In [1]:
from numpy import matrix

In [2]:
m1=matrix([1,2,3,4,5])

In [3]:
print(m1)

[[1 2 3 4 5]]


In [4]:
m1

matrix([[1, 2, 3, 4, 5]])

In [5]:
m1.shape

(1, 5)

In [6]:
L1=[[1,2,3,4],[5,6,7,8]]
m2=matrix(L1)


In [7]:
print(m2)

[[1 2 3 4]
 [5 6 7 8]]


# asmatrix function()

In [8]:
from numpy import asmatrix,arange
m2_array = asmatrix(arange(1,9).reshape(2,4))

In [9]:
print (m2_array)

[[1 2 3 4]
 [5 6 7 8]]


# Excerise 1

In [10]:
#create a two dimeensional matrix m3 the shape of matrix(2,4) with the element of 5,6,7,8,9,10,11,12
#use arange() and reshape() and asmatrix function()

In [11]:
from numpy import asmatrix,arange
m3_array = asmatrix(arange(5,13).reshape(2,4))

In [12]:
m3_array

matrix([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

# Addition of matrix

In [13]:
m2+m3_array

matrix([[ 6,  8, 10, 12],
        [14, 16, 18, 20]])

# subtraction of matrix

In [14]:
m3_array-m2

matrix([[4, 4, 4, 4],
        [4, 4, 4, 4]])

# matiplication of matrix

In [15]:
6.5*m3_array

matrix([[32.5, 39. , 45.5, 52. ],
        [58.5, 65. , 71.5, 78. ]])

In [16]:
m2.shape

(2, 4)

In [19]:
m4 = asmatrix(arange(1,9).reshape(4,2))

In [20]:
m4

matrix([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [21]:
m4.shape

(4, 2)

In [23]:
m3_array*m4

matrix([[114, 140],
        [178, 220]])

In [24]:
print(m4.T) # transport of matrix

[[1 3 5 7]
 [2 4 6 8]]


# Determinanat of the matrix

# Exercise 2

In [25]:
#To find out the determinant of 3X3 matrix
#[[2,-3,1],[2,0,-1],[1,4,5]]

In [26]:
from numpy.linalg import det
m5=matrix([[2,-3,1],[2,0,-1],[1,4,5]])

In [28]:
det(m5)

49.000000000000014

# inverse matrix 

In [33]:
from numpy.linalg import inv


In [34]:
im5 = inv(m5)

In [35]:
im5

matrix([[ 0.08163265,  0.3877551 ,  0.06122449],
        [-0.2244898 ,  0.18367347,  0.08163265],
        [ 0.16326531, -0.2244898 ,  0.12244898]])